// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"database/sql"
)

type Todo struct {
	ID          int64          `json:"id"`
	Title       sql.NullString `json:"title"`
	Description sql.NullString `json:"description"`
	CreateDate  sql.NullTime   `json:"create_date"`
	UpdateDate  sql.NullTime   `json:"update_date"`
}
