// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	ClearTodo(ctx context.Context) error
	CountTodo(ctx context.Context) (int64, error)
	CreateTodo(ctx context.Context, arg CreateTodoParams) (sql.Result, error)
	DeleteTodo(ctx context.Context, id int64) error
	DeleteTodoList(ctx context.Context, ids string) error
	GetTodo(ctx context.Context, id int64) (Todo, error)
	ListTodo(ctx context.Context, arg ListTodoParams) ([]Todo, error)
	UpdateTodo(ctx context.Context, arg UpdateTodoParams) error
}

var _ Querier = (*Queries)(nil)
